In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("Churn_Modelling.csv")

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
x=df.iloc[:,3:13].values
y=df.iloc[:,13].values

In [6]:
x


array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

#Encoding catecrical data

In [7]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
LabelEncoder_x_1=LabelEncoder()

In [8]:
x[:,1]=LabelEncoder_x_1.fit_transform(x[:,1])
LabelEncoder_x_2=LabelEncoder()
x[:,2]=LabelEncoder_x_2.fit_transform(x[:,2])


In [9]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
x_test

array([[597, 1, 0, ..., 1, 1, 192852.67],
       [523, 0, 0, ..., 1, 0, 128702.1],
       [706, 2, 0, ..., 1, 1, 75732.25],
       ...,
       [578, 2, 1, ..., 1, 0, 141533.19],
       [650, 1, 1, ..., 1, 1, 11276.48],
       [573, 1, 1, ..., 1, 0, 192950.6]], dtype=object)

#feature scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

#make the ANN

In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense

#adding input layer and first hidden layer

In [14]:
classifier=Sequential()
classifier.add(Dense(units=6,input_dim=10,activation="relu"))

#adding 2nd layer

In [16]:
classifier.add(Dense(units=6,activation="relu"))

#adding third layer

In [17]:
classifier.add(Dense(units=1,activation="sigmoid"))

In [18]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

#compiling the ANN

In [ ]:
classifier.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 [==============================] - 5s 3ms/step - loss: 0.5111 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4540 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4379 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4298 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4242 - accuracy: 0.7960
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4170 - accuracy: 0.8120
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4081 - accuracy: 0.8189
Epoch 8/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3965 - accuracy: 0.8256
Epoch 9/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3858 - accuracy: 0.8322
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3766 - accura

In [ ]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

In [ ]:
y_pred

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [74]:
cm

array([[1520,   75],
       [ 206,  199]], dtype=int64)